### ISSUE TITLE
When clicking on table button - two click events are happening

### ISSUE THREAD

**Issue by morsh** [CatalystCode/ibex-dashboard#116]
@deadlyfingers - I can't find your code that fixed that (I looked in git history)
Do you remember the fix for that? (I'm working on ibex version 1 branch)

**Comment by deadlyfingers** [comment]
We used `event.stopPropagation()` to stop bubbling the mouse click event.

**Comment by morsh** [comment]
@deadlyfingers - nm, this was on another branch I didn't merge...
