### ISSUE TITLE
REACT_APP_APP_INSIGHTS_APIKEY not working

### ISSUE THREAD

**Issue by morsh** [CatalystCode/ibex-dashboard#12]
Seems that react-scripts does not pick up the key for REACT_APP_APP_INSIGHTS_APIKEY in the right way.

Everything was set correctly but react-scripts didn't pick up the updated value. It kept using the default value set with the ARM deployment.

@daltskin

**Comment by daltskin** [comment]
Just to verify - if you create the App Settings keys (REACT_APP_APP_INSIGHTS_APPID + REACT_APP_APP_INSIGHTS_APIKEY) BEFORE you configure GitHub deployment then readme guide will work.

If you've already deployed the dashboard, then add your App Settings then try changing the values of the above - it does not pick up the latest values.  Even if you try stopping & starting the website.  The workaround is to redploy the website again.  Azure Portal -> Resource Group -> Dashboard App Service -> Deployment Options -> Select last deployment -> Redeploy.

**Comment by morsh** [comment]
This issue is emitted since we no longer keep connection params in environment variables but they are moving to the dashboard configuration.
