### ISSUE TITLE
Enable showing tables without pagination

### ISSUE THREAD

**Issue by morsh** [CatalystCode/ibex-dashboard#124]
Currently, tables do not enable removing pagination altogether.

Plus, rows per page - is a constant that should be received from Props (currently defined in state)

**Comment by deadlyfingers** [comment]
UX: Pagination menu needs fixed so it pops up in the upwards direction as it always positioned at the bottom of the screen.

**Comment by deadlyfingers** [comment]
I think we need to enforce pagination at some point however as it effects UX if we allow too many rows. This is because the component itself is not a recyclable list view and becomes choppy with too many list items...
