### ISSUE TITLE
List of live / active conversations

### ISSUE THREAD

**Issue by deadlyfingers** [CatalystCode/ibex-dashboard#127]
To open dialog with messages that are active so we can initiate hand-off to human.
Perhaps this could be a custom element for this purpose.

**Comment by deadlyfingers** [comment]
We need to look at generalising the components, atm it very tightly coupled to the conversations doc json...

**Comment by morsh** [comment]
@deadlyfingers - not sure I understand. You could get list of messages from DS1:CosmosDB + DS2:AppInsights + DS3: Merge data from both locations and feed that merge into the conversations table.

WDYT?

**Comment by deadlyfingers** [comment]
^ The active conversations (and sentiment) will be queried using Cosmos DB - this will be available as NPM bot handoff package:
https://www.npmjs.com/package/bot_handoff
