### ISSUE TITLE
[Question] Does this project going to be available on botframework.com?

### ISSUE THREAD

**Issue by amitbend** [CatalystCode/ibex-dashboard#146]
Hi,
I couldn't find another place so i'll ask it here - 
Does this project going to be available on botframework.com?

I mean on the analytics tabs when choosing your bot?
If not - i strongly recommend it will

**Comment by morsh** [comment]
Hi @amitbend ,
Although this was an idea the bot framework team played with, this is not currently an approach they are taking. We will have to settle for a separate web app for now :)

**Comment by amitbend** [comment]
@morsh Thanks!
I hope they will integrate it eventually
