### ISSUE TITLE
CSharp Telemetry Plugin Sample Broken Link

### ISSUE THREAD

**Issue by garypretty** [CatalystCode/ibex-dashboard#177]
Hi.  I want to add the additional telemetry for CSharp in terms of intents and sentiment, but the link to the sample seems to be locked down. https://trpp24botsamples.visualstudio.com/_git/Code?path=%2FCSharp%2Fsample-Telemetry&version=GBmaster&_a=contents 

Can you point me to the sample on an alternate link?

**Comment by morsh** [comment]
Hi gary, sorry for the late reply.

this should either be opened or migrated to github.
I'll check and let you know.

**Comment by deadlyfingers** [comment]
@garypretty we have cloned the sample project into public repo for you -
 https://github.com/CatalystCode/bot-sample-telemetry

**Comment by deadlyfingers** [comment]
Once this c# sample is tested with Ibex dashboard we should add the link to the readme to close this issue...

**Comment by garypretty** [comment]
Thanks. I am testing this now. Should I expect to see a delay in the intent and conversation data being populated in the dashboard?  I can see channel hits from the last 2 hours, but no intent / conversation data is showing yet - however, I can see the custom metrics logged in the app insights portal.

**Comment by morsh** [comment]
@itye-msft - can you check this? I think there might be some updates in the schema that weren't included in the C# code.

**Comment by garypretty** [comment]
Hi @morsh @itye-msft Just checking to see if there is any update on this? Released my bot yesterday which uses LUIS pretty heavily so would be great to get more telemetry into the portal.

**Comment by itye-msft** [comment]
Hi @garypretty ,
The C# client is still undergoing some changes and refactoring in order to be aligned with recent changes we made to the Ibex Dashboard. Nevertheless it shouldn't take long to release it. 
I'll keep you posted.

Thanks,
- Itye

**Comment by morsh** [comment]
@garypretty - this is the updated repo for this issue:
https://github.com/CatalystCode/botbuilder-instrumentation-cs

@itye-msft - is there anything more we can share?

**Comment by garypretty** [comment]
Thanks for this. I am now seeing intent information through the dashboard, which is great. However, I am not seeing any conversation data (i.e. the actual messages). In the previous sample you needed to initialize the telemetry logger to do this, but that doesn’t seem to appear in the readme any more.  Any idea why I am not seeing individual messages?

Thanks

Gary

**Comment by itye-msft** [comment]
Hi @garypretty 
The [BotBuilder Instrumentation](https://github.com/CatalystCode/botbuilder-instrumentation-cs) contains only the source code for a DLL to use. The binary can be obtained from nuget as well:
`PM> Install-Package BotBuilder.Instrumentation`
Once instantiated, the library will automatically send conversation data to the telemetry.
All the data will be visible on the Ibex dashboard automatically.

If you want to see a working bot sample which utilizes the BotBuilder.Instrumentation library please refer to:
[https://github.com/itye-msft/Bot-with-instrumentation-cs](https://github.com/itye-msft/Bot-with-instrumentation-cs)

**Comment by garypretty** [comment]
@itye-msft Thanks for the reply. I've looked at the sample and I seem to be doing things right. i.e. I am using the new Instrumented LUIS Dialog and I am seeing the right message counts / intents in the portal, but I am not able to see the actual messages sent back & forth between the bot and the user in the conversations area in the top right of the dashboard.  Do I need to do something additional to enable this / see the conversations in the dashboard?

I know that previously you were using an ActivityLogger middleware to track messages, but in the AlarmBot sample that doesn't seem to be the case.

**Comment by itye-msft** [comment]
@garypretty 
Internally `BotFrameworkApplicationInsightsInstrumentation` starts the monitoring automatically in the constructor by hooking into all conversations using (ActivityLogger)[https://github.com/CatalystCode/botbuilder-instrumentation-cs/blob/master/botbuilder-instumentation/Instumentation/BotFrameworkInstrumentation.cs#L44]. 

We basically encapsulate this to simplify the usage, and it sends all conversations to the telemetry automatically. 

Try to click on `intents graph` as it also shows conversations per intent. 
I will also need to know what dashboard template  were you using (it shows in the title).

Please let me know if that helps.

**Comment by garypretty** [comment]
Thanks. I will check the intents graph.  I am using the Bot Framework Instrumentation Template as far as I know.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by garypretty** [comment]
Hi again. Ok, I checked the intents graph and I am seeing conversations! Sorry, just didn't know you would see them there.  So, the only thing left right now is the top right hand corner of the dashboard seems to be broken, where I had assumed you could click through to conversations. See the attached file.

![2017-07-11_14-53-43](https://user-images.githubusercontent.com/3900649/28071839-17a5df7a-6649-11e7-909b-9b67fb29b289.png)

**Comment by morsh** [comment]
Hi @garypretty - that's the least used feature. 
@itye-msft LMK if this should work - Basically, you need to use startTransaction/endTransaction and the control the conversion rate (not conversations).
That can potentially be used to understand customer converstion statistics.

**Comment by garypretty** [comment]
Got it - my bad, because it had cut off I had misread it as conversations!

Ok, great. So it looks like I have this working now.  I have noticed another couple of things which don't seem to be right.  I am happy to close this issue and raise them as separate issues / changes if you agree that they are currently known issues?

- I am not seeing any entity information in the intent popup window, even though there are entity hits in almost every utterance

- When I filter down by channel and I click an intent I see all conversations / utterances instead of the data being filtered by channel in the same way that the dashboard is.

Hopefully these are things I can help with once I am up to speed on the code!

**Comment by morsh** [comment]
@garypretty - Closing and opening would be awesome.

* Entity info: We've just fixed the instrumentation to support v > 3.7, so it might not be perfect as of yet.
* Filter application in drill down: Haven't thought about this. I'm guessing the fix should be very simple (defining the filters property on the drill down dialogs as well as the root dashboard).

And if you can help with issues, please do! we can use any help you can give :)

**Comment by morsh** [comment]
Closing issue, since this is no longer a direct issue.
