### ISSUE TITLE
export / import data + KQL (embetter) - Possibly according to an addition to templates

### ISSUE THREAD

**Issue by morsh** [CatalystCode/ibex-dashboard#194]

**Comment by deadlyfingers** [comment]
@morsh for each element we want to:
- import / export KQL
- export data (single JSON, maybe multiple CSVs?)

Whats the addition to templates about?

**Comment by morsh** [comment]
@deadlyfingers - Only export KQL (import KQL can be via edit dashboar, so no need).
And addition to templates - Enable a property to each element in the dashboard where you can specify what is to be exported.

On the other hand, that can be a change added to each Component saying what should be the exported data.

**Comment by deadlyfingers** [comment]
![card-settings](https://user-images.githubusercontent.com/1880480/27860327-02e4f88e-6174-11e7-985c-698b90dcac2b.png)
^ This is how the card settings button / card widgets looks - aligned to top right of each element. All these ‘widgets’ only appear when hovering over card now too keep the design clean. Clicking the cog will open dialog with contextual download data options and KQL snippets for copying over to run in App Insights.

**Comment by morsh** [comment]
Can you show the cog only when you hover on the card?

**Comment by deadlyfingers** [comment]
Yip all the widgets positioned in top right including the 'cog' will be hidden until you hover over the card.

**Comment by morsh** [comment]
sounds cool, one thing I'm worried about is having two different export features (one from toolbar dialog, and another from hover on components) which might be confusing.
WDYT?

**Comment by deadlyfingers** [comment]
Agreed, no more need for the toolbar one as it will duplicate functionality. Also it will reduce the amount of toolbar buttons visible - which looks cleaner and avoids confusion with the similar download export dashboard button.

**Comment by deadlyfingers** [comment]
I have one proposal for 'export' schema to help with figuring out what data sources should be shown (in key-value format where key is datasource id and value is the user readable description of the data)
```
export: {
  'timeline-users-graphData': "Timeline of users on each channel",
  'timeline-channels': "List of channels",
}
```
^ Anything not included here could be ignored. For example 'timeline-channels' is not very useful and could be dropped from download options as it will rarely change form a simple array of channels used.

**Comment by morsh** [comment]
@deadlyfingers - If we chose only one source for each graph, can we drop the needs for change in the template?
We have quite a few templates, and their confusing as it it. So it can be nice to have an option to export more than one data source, but I think one should be enough. The title can just be the title of the exported components.
The only issue is how to export the KQL...
Do you have any ideas?

**Comment by deadlyfingers** [comment]
Ok, I think we can best guess this without template change as you mention. We can grab each json used by the chart and simply order them based on size. Therefore when you open the dialog it will automatically show the data / query of most interest. The dialog toolbar can have a select to change json source if need be...

**Comment by deadlyfingers** [comment]
I can get the queries as function types, so trying to flatten them out as strings to be able to copy the queries out for use in App Insights. The problem is passing the required vars into function to render it correctly.

**Comment by deadlyfingers** [comment]
![card-widget-dialog](https://user-images.githubusercontent.com/1880480/27968419-d084b4de-633e-11e7-8a45-47c4e65376b0.png)
- Data uses JSON formatting, and plain text for the query
- Download json (scorecard values are grouped into JSON key:value format)
- Copy data and query buttons

**Comment by deadlyfingers** [comment]
TODO: 
- refactor any Application Insights specific code in SettingsStore into AI plugin methods.
- add KQL line returns after comma delimiters
- hide card widgets until data has loaded...

V2 features?
- run AI query within dialog to see results preview
- look into basic colour coding for query
