### ISSUE TITLE
Fix Dialog filters

### ISSUE THREAD

**Issue by deadlyfingers** [CatalystCode/ibex-dashboard#262]
While the selected filters can be passed into the dialog context the filter isn't being applied within a dialog query.

**Comment by deadlyfingers** [comment]
Update: this issue is caused when using an unforked query as the filter is inserted ahead of the table name in this case.

**Comment by garypretty** [comment]
Thanks. Will implement the changes locally and test.

Do you have a filter type available which is a date picker? Would that be easy to implement?

Gary

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by morsh** [comment]
Hi @deadlyfingers & @garypretty,
Was this solved by the latest PR?

**Comment by deadlyfingers** [comment]
Yip, we can close this.
