### ISSUE TITLE
Add info balloons when hovering on the icons in create dashboard page

### ISSUE THREAD

**Issue by Ilanak** [CatalystCode/ibex-dashboard#268]
![image](https://user-images.githubusercontent.com/13463870/29119054-3f1b18d8-7d0d-11e7-97bf-db2fb438383b.png)

screenshot with suggestion attached

**Comment by deadlyfingers** [comment]
We can add tooltip prop to the icon buttons .

**Comment by deadlyfingers** [comment]
Closing issue, as this has been completed as part of UX improvements in PR #325.
