### ISSUE TITLE
Make design more minimalist

### ISSUE THREAD

**Issue by morsh** [CatalystCode/ibex-dashboard#27]
- Move subtitles as info icons next to title
- Make title a lot smaller
- Make fonts aligned with Segoe?

**Comment by deadlyfingers** [comment]
Instead of Segoe as it is under license... wonder if we are better using Selawik - an open source version?
https://github.com/winjs/winstrap/tree/master/dist/fonts

**Comment by morsh** [comment]
@deadlyfingers - what would it take to change the font?

**Comment by deadlyfingers** [comment]
Should be a case of defining a font face in SASS. Material Design is heavily linked with Roboto but I know react-md mentions SASS theming support so it should work ok. 
@morsh I can look at this if you want - the first couple of items you have already done, right?

**Comment by morsh** [comment]
@deadlyfingers - Yeah, I only now read the original issue... actually, on second thought, this is a little redundant, we didn't get any ask for this or anything, I think we can let this one go...
