### ISSUE TITLE
Error when loading dashboard

### ISSUE THREAD

**Issue by eladiw** [CatalystCode/ibex-dashboard#272]
Created a new 'bot basic dashboard'.
(It didn't load well - another issue on that).
I saw on the developers tools the following error:

**_ReferenceError: A store named SettingsStore already exists, double check your store names or pass in your own custom identifier for each store
    at Object.a [as warn] (main.90c1f23b.js:19)
    at e [as createStore] (main.90c1f23b.js:57)
    at Object.<anonymous> (main.90c1f23b.js:91)
    at t (main.90c1f23b.js:1)
    at Object.<anonymous> (main.90c1f23b.js:88)
    at t (main.90c1f23b.js:1)
    at Object.<anonymous> (main.90c1f23b.js:56)
    at t (main.90c1f23b.js:1)
    at Object.<anonymous> (main.90c1f23b.js:88)
    at t (main.90c1f23b.js:1)
a @ main.90c1f23b.js:19_**

**Comment by morsh** [comment]
@eladiw - is this due to dashboard name? Or another reason?
+ Not completely sure what are the parameters you used for creation:
* Exact template name (there are a few bot templates)
* name + id + url you used

**Comment by eladiw** [comment]
@morsh  I will reproduce and mention all the different params...

**Comment by deadlyfingers** [comment]
Another related bug - when creating a dashboard from a template you get a prop error.
```
Warning: Failed prop type: You provided a `type` prop to the Drawer without the `onMediaTypeChange` handler. The `onMediaTypeChange` prop must be specified when the `type` is not one of the `temporary` types.
    in Drawer (created by InfoDrawer)
    in InfoDrawer (created by AIConnectionEditor)
    in div (created by Paper)
    in Paper (created by Card)
    in Card (created by AIConnectionEditor)
    in AIConnectionEditor (created by ConnectionsSettings)
    in div (created by ConnectionsSettings)
    in div (created by ConnectionsSettings)
    in ConnectionsSettings (created by SetupDashboard)
    in div (created by SetupDashboard)
    in SetupDashboard (created by Dashboard)
    in Dashboard (created by RouterContext)
    in ReactCSSTransitionGroupChild (created by ReactTransitionGroup)
    in main (created by ReactTransitionGroup)
    in ReactTransitionGroup (created by ReactCSSTransitionGroup)
    in ReactCSSTransitionGroup (created by NavigationDrawer)
    in div (created by NavigationDrawer)
    in NavigationDrawer (created by Navbar)
    in div (created by Navbar)
    in Navbar (created by App)
    in div (created by App)
    in App (created by RouterContext)
    in RouterContext (created by Router)
    in Router
```

**Comment by morsh** [comment]
@eladiw - It seemed like the problem you fixed is the problem @deadlyfingers wrote about and not the original one

**Comment by eladiw** [comment]
i think there is a duplicate issue, because i wrote it. yes the original issue does not appear any more. I've fixed the second one

**Comment by morsh** [comment]
Ok cool
