### ISSUE TITLE
Layout is saved incorrectly when exitting dashboard edit mode

### ISSUE THREAD

**Issue by rabee333** [CatalystCode/ibex-dashboard#273]
[mor] should check for new version of react-grid-layout - only update in case this update should take up to a day.

Scenario:
1. Enter the Edit mode of an existing dashboard
2. Change the places/sizes of the components.
3. Click on the connection settings button, and click cancel (or save) in the opened window.
4. Click on Finish Editing button.

Note that the layout of the UI components was not saved as expected. It was changed and left some empty spaces before and between the components.

**Comment by deadlyfingers** [comment]
Updating react-grid-layout to latest version `"react-grid-layout": "^0.14.7"` seems to save layout ok.

**Comment by deadlyfingers** [comment]
NB: If you click 'save' the edits are not saved, but cancel is ok.
