### ISSUE TITLE
Hard to understand 'dashboard icon'

### ISSUE THREAD

**Issue by eladiw** [CatalystCode/ibex-dashboard#275]
when you create a new dashboard it asks for a dashboard icon.
its a free text field.

if you choose unsupported string it just gives you the default which is 'dashboard'.
users won't normally know what options they have.
I suggest two options:
a) keep it free text and put a link to the complete list of icons 
b) preferred option - put a drop down with top X options. no free text

**Comment by deadlyfingers** [comment]
All the icons available:
https://material.io/icons/

**Comment by deadlyfingers** [comment]
![screen shot 2017-08-24 at 18 21 52](https://user-images.githubusercontent.com/1880480/29679266-360e6626-88f9-11e7-8630-bd724e1c2b1b.png)
