### ISSUE TITLE
Nan Value in conversations charts

### ISSUE THREAD

**Issue by eladiw** [CatalystCode/ibex-dashboard#276]
![image](https://user-images.githubusercontent.com/13205761/29120865-e13cd690-7d14-11e7-939b-4febce1e78bc.png)

In this case I believe that it should state 0.
There is no meaning for Nan Conversations.

**Comment by eladiw** [comment]
actually, what does it even mean? what is 50% conversations?
I think it should be more elaborated or self explanatory

**Comment by morsh** [comment]
@eladiw - 50% of user interactions completed with a conversion

**Comment by deadlyfingers** [comment]
@morsh we can also add the scorecard tooltip to help explain. 
(Scorecard tooltips example in QnA template)

**Comment by deadlyfingers** [comment]
![screen shot 2017-08-14 at 15 27 38](https://user-images.githubusercontent.com/1880480/29276017-23188cfa-8105-11e7-8176-ba8a16a27b9d.png)
