### ISSUE TITLE
Gear icon is not very suitable

### ISSUE THREAD

**Issue by eladiw** [CatalystCode/ibex-dashboard#278]
when you click the gear icon you see the underlying data.
however gear usually represents a configuration is possible ...
![image](https://user-images.githubusercontent.com/13205761/29121075-b59e5f80-7d15-11e7-8140-87dd9916f9e2.png)

I would change it to something a bit different

**Comment by deadlyfingers** [comment]
Possible replacements we can use are on https://material.io/icons/ - alternative suggestions:
input
call_made
search

**Comment by deadlyfingers** [comment]
Now using expand more arrow - 
![screen shot 2017-08-14 at 14 59 28](https://user-images.githubusercontent.com/1880480/29274886-3bbf5dfa-8101-11e7-8597-cf4928e19013.png)
