### ISSUE TITLE
Missing documentation for creating custom dashboard elements

### ISSUE THREAD

**Issue by Ilanak** [CatalystCode/ibex-dashboard#287]
Consider adding to the documentation samples for simple AppInsights elements example:

dataSources: [
    {
      id: "timespan", // Add time picker options
      type: "Constant",
      params: { values: ["24 hours", "1 week", "1 month", "3 months"], selectedValue: "24 hours" },
      format: "timespan"
    },
    {
      id: "someid",
      type: "ApplicationInsights/Query",
      dependencies: { timespan: "timespan", queryTimespan: "timespan:queryTimespan", granularity: "timespan:granularity" },
      params: {
        table: "requests", // table name
        queries: {
          failures: { // QueryName
            query: () => ` where success == 'False' | summarize count = count()`, // Application Insights query
            format: {
              type: "scorecard",
              args: { postfix: "%", thresholds: [{ value: 0, color: "#2196F3", icon: "input", heading: "Failures" }] }
            }
          }
        }
      }
    }
  ],
  filters: [
    {
      type: "TextFilter",
      title: "Timespan",
      source: "timespan",
      actions: { onChange: "timespan:updateSelectedValue" },
      first: true
    }
  ],
  elements: [
    {
      id: "scores",
      type: "Scorecard",
      size: { w: 4, h: 3 },
      source: { failures: "filters:failures" } // source can contain more than one 
    }
  ]

**Comment by morsh** [comment]
Closing this since #299 is taking care of this issue.
