### ISSUE TITLE
Add additional graph components

### ISSUE THREAD

**Issue by morsh** [CatalystCode/ibex-dashboard#63]
Currently to add:
http://recharts.org/#/en-US/examples/SimpleRadialBarChart
http://recharts.org/#/en-US/examples/SimpleRadarChart

**Comment by deadlyfingers** [comment]
http://recharts.org/#/en-US/api/RadarChart

**Comment by gregdegruy** [comment]
Leave it to me 👍

**Comment by deadlyfingers** [comment]
Closing, this has been added.
