### ISSUE TITLE
Create Dashboard - Create basic dashboard for MBF

### ISSUE THREAD

**Issue by morsh** [CatalystCode/ibex-dashboard#75]
Create a dashboard which is not reliant upon augmented data that contains:
* Timeline Users + Messages
* Exception
* User retention (new / returning users)
* Total Users/Messages per channel

**Comment by gregdegruy** [comment]
taking this on 
👍

**Comment by gregdegruy** [comment]
Create a dashboard which is not reliant upon augmented data that contains:
	
	Timeline with Users + Messages
		?

	Exception
		NEW
		Drill down
			Timestamps for exceptions

	User retention (new / returning users)
		Retention table format
		time stamp	retention    new-users
		24 hours		50%            5k
		7 days		40%	           8k
		30 days		70%	           30k
		
	Total Users/Messages per channel
		Have message count in Channel Usage Pie Chart, 
		need the number of users on each channel

**Comment by gregdegruy** [comment]
PR #102
